<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vengadores [

	<!ELEMENT vengadores (vengador*,trajes)>
	<!ELEMENT vengador (poder, equipo, arma)>
	<!ELEMENT trajes (traje+)>
	<!ELEMENT traje EMPTY>
	<!ELEMENT poder EMPTY>
	<!ELEMENT arma EMPTY>
	<!ELEMENT traduccion EMPTY>
	<!ELEMENT equipo (#PCDATA | traduccion)*>
	
	<!ATTLIST vengador 	nombre CDATA #REQUIRED 
						referencia ID #REQUIRED 
						compa単ia CDATA #IMPLIED>
						
	<!ATTLIST equipo nombre CDATA #FIXED "AVENGERS">
	<!ATTLIST arma tipo (Lanzaredes | Escudo | Misiles) #IMPLIED>
	<!ATTLIST traje propiedad IDREF #REQUIRED>
	<!ENTITY LV "Los Vengadores">
	<!ENTITY % poderHeroe "<!ATTLIST poder tipo CDATA #IMPLIED>">
	%poderHeroe;
]>

<vengadores>

	<vengador nombre="Spider Man" referencia="v1" compa単ia="Marvel">
		<poder tipo="Reflejos Aracnidos" />
		<equipo nombre="AVENGERS">&LV; <traduccion/></equipo>
		<arma tipo="Lanzaredes"/>
	</vengador>
	
	<vengador nombre="Capitan America" referencia="v2" compa単ia="Marvel">
		<poder tipo="Fuerza" />
		<equipo nombre="AVENGERS">&LV;<traduccion/></equipo>
		<arma tipo="Escudo"/>
	</vengador>
	
	<vengador nombre="Iron Man" referencia="v3" compa単ia="Marvel">
		<poder tipo="Armadura" />
		<equipo nombre="AVENGERS">&LV; <traduccion/></equipo>
		<arma tipo="Misiles"/>
	</vengador>
	
	<trajes>
		<traje propiedad="v1"/>
		<traje propiedad="v2"/>
		<traje propiedad="v3"/>
	</trajes>
	
</vengadores>