=== danimc97/Mis_Apuntes_LM/Proyecto LM/src/ExamenDTD2018/ExamenDTD2018.dtd
<!ELEMENT movil (accesorios, extras?, referencias)>
<!ELEMENT accesorios (accesorio+)>
<!ELEMENT accesorio (#PCDATA | id )*>
<!ELEMENT id EMPTY>
<!ELEMENT extras (accesorioExtra*, (accesoriosSorpresa | accesoriosSorpresa1)+)>
<!ELEMENT accesorioExtra (#PCDATA)>
<!ELEMENT accesoriosSorpresa (#PCDATA)>
<!ELEMENT accesoriosSorpresa1 (#PCDATA)>
<!ELEMENT referencias (referenciaAccesorio*)>
<!ELEMENT referenciaAccesorio EMPTY>

<!ENTITY CAR "Cargador">

<!ENTITY % propiedades "referencia IDREF #REQUIRED
					color (Negro | Blanco | Transparente) #IMPLIED">
					
<!ENTITY % propiedadesS "referencia IDREFS #REQUIRED
					color (Negro | Blanco | Transparente) #IMPLIED">
					
<!ATTLIST id tipo CDATA #REQUIRED>

<!ATTLIST accesorio %propiedades;>
					
<!ATTLIST accesorioExtra %propiedades;>
							
<!ATTLIST accesoriosSorpresa %propiedadesS;>
							
<!ATTLIST accesoriosSorpresa1 %propiedadesS;>
							
<!ATTLIST referenciaAccesorio 	tipo ID #REQUIRED
								marca CDATA #FIXED "Samsung">

=== danimc97/Mis_Apuntes_LM/Proyecto LM/src/ExamenDTD2018/ExamenDTD2018.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE movil SYSTEM "ExamenDTD2018.dtd">

<movil>

	<accesorios>
	
		<accesorio  referencia="Carga" color="Negro">&CAR; de movil<id tipo="Codigo de barras"/></accesorio>
		<accesorio  referencia="Sonido" color="Blanco">Auriculares<id tipo="Codigo de barras"/></accesorio>
		<accesorio  referencia="Proteccion" color="Transparente">Protector de pantalla<id tipo="Codigo de barras"/></accesorio>
	
	</accesorios>
	
	<extras>
	
		<accesorioExtra referencia="Carga" color="Negro">&CAR; portatil</accesorioExtra>
		<accesorioExtra referencia="Sonido" color="Negro">Auriculares</accesorioExtra>
		<accesorioExtra referencia="Proteccion" color="Negro">Protector de pantalla</accesorioExtra>
		<accesorioExtra referencia="Carga" color="Negro">&CAR; portatil</accesorioExtra>
		<accesoriosSorpresa1 referencia="Proteccion Carga" color="Negro">Funda de movil y protector</accesoriosSorpresa1>
		
	</extras>
	
	
	<referencias>
		
		<referenciaAccesorio tipo="Carga" marca="Samsung"/>
		<referenciaAccesorio tipo="Sonido" marca="Samsung"/>
		<referenciaAccesorio tipo="Proteccion" marca="Samsung"/>
	
	</referencias>

</movil>
