=== danimc97/Mis_Apuntes_LM/Proyecto LM/src/ExamenDTD/PruebaExamen1.dtd
<!ELEMENT tienda (peluches?, tazas?, cestas?, productos?)*>
<!ELEMENT peluches (peluche+)>
<!ELEMENT peluche (#PCDATA)>
<!ELEMENT tazas (taza+)>
<!ELEMENT taza (#PCDATA | personaje)*>
<!ELEMENT personaje EMPTY>
<!ELEMENT cestas (cesta)>
<!ELEMENT cesta (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto EMPTY>

<!ATTLIST peluche %product;>					
<!ATTLIST taza 	%product;>
					
<!ATTLIST cesta precio (15 | 13 | 10 | 20) #REQUIRED referencia IDREFS #REQUIRED nombre CDATA #IMPLIED>
<!ATTLIST personaje nombre CDATA #IMPLIED>

<!ATTLIST producto 	tipo ID #REQUIRED>

<!ENTITY taza "taza">
<!ENTITY peluche "peluche">

<!ENTITY % product "precio (15 | 13 | 10 | 20) #REQUIRED referencia IDREF #REQUIRED nombre CDATA #IMPLIED">

=== danimc97/Mis_Apuntes_LM/Proyecto LM/src/ExamenDTD/PruebaExamen1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tienda SYSTEM "PruebaExamen1.dtd">

<tienda>
	<peluches>
		<peluche precio="15" referencia="peluche" nombre="Oso">Oso de &peluche;</peluche>
		<peluche precio="13" referencia="peluche" nombre="Caballo">Caballo de &peluche;</peluche>
	</peluches>
	
	<tazas>
		<taza precio="10" referencia="taza" nombre="Futurama">&taza;de Futurama <personaje nombre="Bender"/></taza>
		<taza precio="10" referencia="taza" nombre="Batman">&taza; de Batman <personaje nombre="joker"/></taza>
	</tazas>
	
	<cestas>
	
		<cesta precio="20" referencia="taza peluche" nombre="CestaRegalo">Cesta con un &peluche; y una &taza;</cesta>
	
	</cestas>
	
	<productos>
		<producto tipo="peluche"/>
		<producto tipo="taza"/>
	</productos>
</tienda>
