=== danimc97/Mis_Apuntes_LM/Proyecto LM/src/ExamenDTD1/Examen.dtd
<!ELEMENT pelicula (titulo, sinopsis, reparto, personajes+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT reparto (actor?, actriz?)*>
<!ELEMENT actor (#PCDATA | papel)*>
<!ELEMENT actriz (#PCDATA | papel)*>
<!ELEMENT papel EMPTY>
<!ELEMENT personajes (personaje*)>
<!ELEMENT personaje EMPTY>

<!ENTITY % propiedades "interpreta_a CDATA #REQUIRED
				edad CDATA #FIXED '19'
				pais CDATA #REQUIRED">

<!ATTLIST actor %propiedades;>
				
<!ATTLIST actriz %propiedades;>
				
<!ATTLIST papel tipo IDREF #REQUIRED>

<!ATTLIST personaje importancia ID #REQUIRED>

<!ENTITY SM "Spider-Man">

=== danimc97/Mis_Apuntes_LM/Proyecto LM/src/ExamenDTD1/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pelicula SYSTEM "Examen.dtd">

<pelicula>

	<titulo>&SM; Homecoming</titulo>
	
	<sinopsis>Un tio que le pica una ara√±a y ala tiene poderes guapos</sinopsis>
	
	<reparto>
	
		<actor interpreta_a="Spider-Man" edad="19" pais="USA">Tom Holland<papel tipo="primario"/></actor>
		<actriz interpreta_a="Michelle" edad="19" pais="USA">Zendaya<papel tipo="secundario"/></actriz>
		<actriz interpreta_a="Liz" edad="19" pais="USA">Laura Harrier<papel tipo="primario"/></actriz>
	
	</reparto>
	
	<personajes>
	
		<personaje importancia="primario"/>
		<personaje importancia="secundario"/>
	
	</personajes>

</pelicula>
